
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

[types]

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.endlessbiomes]
			penumbral = true
			glowing_penumbral = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.integrateddynamics]
			menril = true

	[types.wood_type]

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.gardens_of_the_dead]
			soulblight = true
			whistlecane = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.endlessbiomes]
			penumbra = true
			twisted = true

		[types.wood_type.ars_nouveau]
			archwood = true

	[types.cake]

		[types.cake.blue_skies]
			comet_berry_pie = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.mcwdoors]
			beach_door = true
			nether_door = true
			stable_head_door = true
			barn_door = true
			mystic_door = true
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			cottage_door = true
			four_panel_door = true
			japanese_door = true
			western_door = true
			bark_glass_door = true
			paper_door = true
			classic_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			stable_door = true
			modern_door = true

		[entries.wood_type.mcwbridges]
			log_bridge_stair = true
			rail_bridge = true
			bridge_pier = true
			rope_bridge = true
			rope_bridge_stair = true
			log_bridge_middle = true

		[entries.wood_type.mcwfences]
			horse_fence = true
			highley_gate = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true
			picket_fence = true

	[entries.leaves_type]

		[entries.leaves_type.mcwfences]
			hedge = true

